import os

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Visualizzazione(object):
    def setupUi(self, Visualizzazione):
        Visualizzazione.setObjectName("Visualizzazione")
        Visualizzazione.resize(570, 430)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Visualizzazione)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lab_risultati = QtWidgets.QLabel(Visualizzazione)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lab_risultati.setFont(font)
        self.lab_risultati.setObjectName("lab_risultati")
        self.verticalLayout_2.addWidget(self.lab_risultati)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab_precisioneTraining = QtWidgets.QLabel(Visualizzazione)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_precisioneTraining.setFont(font)
        self.lab_precisioneTraining.setObjectName("lab_precisioneTraining")
        self.verticalLayout.addWidget(self.lab_precisioneTraining)
        self.precisioneTraining = QtWidgets.QLabel(Visualizzazione)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.precisioneTraining.setFont(font)
        self.precisioneTraining.setObjectName("precisioneTraining")
        self.verticalLayout.addWidget(self.precisioneTraining)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lab_precisioneTest = QtWidgets.QLabel(Visualizzazione)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_precisioneTest.setFont(font)
        self.lab_precisioneTest.setObjectName("lab_precisioneTest")
        self.verticalLayout_4.addWidget(self.lab_precisioneTest)
        self.precisioneTest = QtWidgets.QLabel(Visualizzazione)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.precisioneTest.setFont(font)
        self.precisioneTest.setObjectName("precisioneTest")
        self.verticalLayout_4.addWidget(self.precisioneTest)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.img_graph = QtWidgets.QLabel(Visualizzazione)
        self.img_graph.setText("")
        self.img_graph.setScaledContents(True)
        self.img_graph.setWordWrap(True)
        self.img_graph.setOpenExternalLinks(True)
        self.img_graph.setObjectName("img_graph")
        self.verticalLayout_2.addWidget(self.img_graph)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tempo = QtWidgets.QLabel(Visualizzazione)
        self.tempo.setFont(font)
        self.tempo.setText("")
        self.tempo.setObjectName("tempo")
        self.comunicazione = QtWidgets.QLabel(Visualizzazione)
        self.comunicazione.setEnabled(True)
        palette = QtGui.QPalette()
        paletteNero = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brushNero = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brushNero.setStyle(QtCore.Qt.SolidPattern)
        paletteNero.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brushNero)
        paletteNero.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brushNero)
        self.tempo.setPalette(paletteNero)
        self.comunicazione.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comunicazione.setFont(font)
        self.comunicazione.setText("")
        self.comunicazione.setObjectName("comunicazione")
        self.horizontalLayout_3.addWidget(self.comunicazione)
        self.verticalLayout_2.addWidget(self.tempo)
        self.but_previsione = QtWidgets.QPushButton(Visualizzazione)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_previsione.setFont(font)
        self.but_previsione.setObjectName("but_previsione")
        self.but_previsione.clicked.connect(Visualizzazione.previsione)
        self.horizontalLayout_3.addWidget(self.but_previsione)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        currentDir = os.path.dirname(os.path.abspath(__file__))
        pathIcon = os.path.join(currentDir, 'img','icon','prediction.ico')
        Visualizzazione.setWindowIcon(QtGui.QIcon(pathIcon))

        self.retranslateUi(Visualizzazione)
        QtCore.QMetaObject.connectSlotsByName(Visualizzazione)

    def retranslateUi(self, Visualizzazione):
        _translate = QtCore.QCoreApplication.translate
        Visualizzazione.setWindowTitle(_translate("Visualizzazione", "Visualizzazione del Training"))
        self.lab_risultati.setText(_translate("Visualizzazione", "Risultati"))
        self.lab_precisioneTraining.setText(_translate("Visualizzazione", "Precisione del training:"))
        self.precisioneTraining.setText(_translate("Visualizzazione", "TextLabel"))
        self.lab_precisioneTest.setText(_translate("Visualizzazione", "Precisione del Test:"))
        self.precisioneTest.setText(_translate("Visualizzazione", "TextLabel"))
        self.but_previsione.setText(_translate("Visualizzazione", "previsione"))
        self.tempo.setText(_translate("Visualizzazione", "TextLabel"))
